# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='TagWiki',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tags',
            name='Tag',
            field=models.CharField(max_length=50),
        ),
    ]
