# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_auto_20180208_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_postidtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=2)),
                ('postidtype', models.CharField(max_length=2)),
            ],
        ),
    ]
