# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0003_id_postidtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='id_postidtype',
            new_name='id_postidtypes',
        ),
    ]
