# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0004_auto_20180302_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='tagPairCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35)),
                ('simiTag', models.CharField(max_length=35)),
                ('compare', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='id_postidtypes',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
