# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0009_auto_20180311_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='example',
            field=models.CharField(max_length=60000),
        ),
        migrations.AlterField(
            model_name='relation',
            name='example_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='relation',
            name='quality',
            field=models.CharField(max_length=1000),
        ),
    ]
