# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0010_auto_20180411_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='example_id',
            field=models.CharField(max_length=600),
        ),
    ]
